name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build and Test with Maven
      - name: Build and Test with Maven
        run: mvn clean package

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: docker build -t kotaderg/java-demo:latest .

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push kotaderg/java-demo:latest
